disabled_rules:
  - trailing_whitespace
  - identifier_name
  - type_name

line_length:
  warning: 150
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true
