version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 12.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test

    steps:
      - checkout
      - run: sudo defaults write com.apple.dt.Xcode IDEPackageSupportUseBuiltinSCM YES
      - run: rm ~/.ssh/id_rsa || true
      - run: for ip in $(dig @8.8.8.8 bitbucket.org +short); do ssh-keyscan bitbucket.org,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
      - run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
      - run:
          command: bundle check || bundle install

      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE

      - store_artifacts:
          path: output/FaceStickerMaker.ipa

      - store_test_results:
          path: output/scan

  beta:
    macos:
      xcode: 12.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: beta

    steps:
      - checkout
      - run: sudo defaults write com.apple.dt.Xcode IDEPackageSupportUseBuiltinSCM YES
      - run: rm ~/.ssh/id_rsa || true
      - run: for ip in $(dig @8.8.8.8 bitbucket.org +short); do ssh-keyscan bitbucket.org,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
      - run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
      - run:
          command: bundle check || bundle install

      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE

      - store_artifacts:
          path: output/FaceStickerMaker.ipa

  prod:
    macos:
      xcode: 12.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: prod

    steps:
      - checkout
      - run: sudo defaults write com.apple.dt.Xcode IDEPackageSupportUseBuiltinSCM YES
      - run: rm ~/.ssh/id_rsa || true
      - run: for ip in $(dig @8.8.8.8 bitbucket.org +short); do ssh-keyscan bitbucket.org,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
      - run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
      - run:
          command: bundle install

      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE

workflows:
  version: 2.1
  build-test-beta-release:
    jobs:
      - hold:
          type: approval
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

      - build-and-test:
          filters:
            branches:
              only:
                - main
                - /^RC.*/

      - beta:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - /^RC.*/

      - prod:
          requires:
            - hold
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
