# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "600"

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Run unit tests"
  lane :test do
    scan
  end

  desc "Setup provisioning profiles and certificates"
  lane :bootstrap do
    match(type: "development", app_identifier: "au.com.incrementaldigital.FaceStickerMaker.dev")
    match(type: "development", app_identifier: "au.com.incrementaldigital.FaceStickerMaker.dev.Stickers")
    match(type: "appstore", app_identifier: "au.com.incrementaldigital.FaceStickerMaker")
    match(type: "appstore", app_identifier: "au.com.incrementaldigital.FaceStickerMaker.Stickers")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore", app_identifier: "au.com.incrementaldigital.FaceStickerMaker")
    match(type: "appstore", app_identifier: "au.com.incrementaldigital.FaceStickerMaker.Stickers")
    build_app(scheme: "FaceStickerMaker")
    upload_to_testflight
    increment_build_number
  end

  desc "Release the most recent beta build"
  lane :prod do
    deliver(
      build_number: latest_testflight_build_number.to_s,
      submit_for_review: true,
      automatic_release: true,
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: false,
      submission_information: {
        add_id_info_uses_idfa: false
      }
    )
  end
end
